import { Category, PartOfSpeech } from './types';

export const POS_LABELS: Record<PartOfSpeech, { label: string; color: string }> = {
  noun: { label: 'Noun', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  verb: { label: 'Verb', color: 'bg-red-100 text-red-800 border-red-200' },
  adj: { label: 'Adjective', color: 'bg-green-100 text-green-800 border-green-200' },
  adv: { label: 'Adverb', color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  pron: { label: 'Pronoun', color: 'bg-purple-100 text-purple-800 border-purple-200' },
  prep: { label: 'Preposition', color: 'bg-gray-100 text-gray-800 border-gray-200' },
  num: { label: 'Number', color: 'bg-indigo-100 text-indigo-800 border-indigo-200' },
  other: { label: 'Other', color: 'bg-teal-100 text-teal-800 border-teal-200' },
};

// --- PASTE YOUR JSON DATA BELOW ---
export const INITIAL_DATA: Category[] = [
  {
    "category": "Time: Days, Months & Seasons (时间：星期/月份/季节)",
    "items": [
      { "lemma": "понеде́льник", "translation": "星期一", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вто́рник", "translation": "星期二", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "среда́", "translation": "星期三", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "четве́рг", "translation": "星期四", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "воскресе́нье", "translation": "星期日", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "янва́рь", "translation": "一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "февра́ль", "translation": "二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "март", "translation": "三月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "апре́ль", "translation": "四月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "май", "translation": "五月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ию́нь", "translation": "六月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ию́ль", "translation": "七月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "а́вгуст", "translation": "八月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сентя́брь", "translation": "九月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "октя́брь", "translation": "十月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ноя́брь", "translation": "十一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дека́брь", "translation": "十二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "весна́", "translation": "春天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ле́то", "translation": "夏天", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "о́сень", "translation": "秋天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "зима́", "translation": "冬天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "вре́мя", "translation": "时间", "pos": "noun", "grammar": { "gender": "n", "special": "-мя" } }
    ]
  },
  {
    "category": "Verbs (核心动词)",
    "items": [
      { "lemma": "учи́ться", "translation": "学习 (在某处)", "pos": "verb", "forms": ["учу́сь", "у́чишься", "у́чатся"], "syntax_note": "vi + 6g (在...)" },
      { "lemma": "учи́ть", "translation": "学习 (背诵/教授)", "pos": "verb", "forms": ["учу́", "у́чишь"], "syntax_note": "vt + 4g (学什么)" },
      { "lemma": "изуча́ть", "translation": "研究，钻研", "pos": "verb", "forms": ["изуча́ю"], "syntax_note": "vt + 4g" },
      { "lemma": "занима́ться", "translation": "从事，做功课", "pos": "verb", "forms": ["занима́юсь"], "syntax_note": "vi + 5g" },
      { "lemma": "люби́ть", "translation": "爱", "pos": "verb", "forms": ["люблю́", "лю́бишь"], "syntax_note": "+ vt / n." },
      { "lemma": "хоте́ть", "translation": "想要", "pos": "verb", "forms": ["хочу́", "хо́чешь", "хотя́т"], "syntax_note": "混合变位" },
      { "lemma": "говори́ть", "translation": "说", "pos": "verb", "forms": ["говорю́", "говори́шь"], "syntax_note": "vi/vt" },
      { "lemma": "сказа́ть", "translation": "说 (命令式)", "pos": "verb", "forms": ["скажи́", "скажи́те"], "syntax_note": "完成体" },
      { "lemma": "ви́деть", "translation": "看见", "pos": "verb", "forms": ["ви́жу", "ви́дишь", "ви́дят"], "syntax_note": "vt" },
      { "lemma": "смотре́ть", "translation": "看 (观看)", "pos": "verb", "forms": ["смотрю́", "смо́тришь"], "syntax_note": "vt" },
      { "lemma": "слу́шать", "translation": "听", "pos": "verb", "forms": ["слу́шаю"], "syntax_note": "vt" },
      { "lemma": "слы́шать", "translation": "听见", "pos": "verb", "forms": ["слы́шу"], "syntax_note": "(图外补充，常与слушать对比)" },
      { "lemma": "стоя́ть", "translation": "站立", "pos": "verb", "forms": ["стою́", "стои́шь"], "syntax_note": "vi + 6g" },
      { "lemma": "лежа́ть", "translation": "平放，躺", "pos": "verb", "forms": ["лежу́", "лежи́шь"], "syntax_note": "vi + 6g" },
      { "lemma": "сиде́ть", "translation": "坐", "pos": "verb", "forms": ["сижу́", "сиди́шь"], "syntax_note": "vi" },
      { "lemma": "идти́", "translation": "走 (正在进行)", "pos": "verb", "forms": ["иду́", "идёшь"], "syntax_note": "Motion" },
      { "lemma": "е́хать", "translation": "乘车去", "pos": "verb", "forms": ["е́ду", "е́дешь"], "syntax_note": "Motion" },
      { "lemma": "лете́ть", "translation": "飞", "pos": "verb", "forms": ["лечу́", "лети́шь"], "syntax_note": "Motion" },
      { "lemma": "гуля́ть", "translation": "散步", "pos": "verb", "forms": ["гуля́ю"], "syntax_note": "vi + 6g (在...散步)" },
      { "lemma": "встава́ть", "translation": "起床", "pos": "verb", "forms": ["встаю́", "встаёшь"], "syntax_note": "" },
      { "lemma": "за́втракать", "translation": "吃早饭", "pos": "verb", "forms": ["за́втракаю"], "syntax_note": "" },
      { "lemma": "обе́дать", "translation": "吃午饭", "pos": "verb", "forms": ["обе́даю"], "syntax_note": "" },
      { "lemma": "у́жинать", "translation": "吃晚饭", "pos": "verb", "forms": ["у́жинаю"], "syntax_note": "" },
      { "lemma": "покупа́ть", "translation": "购买", "pos": "verb", "forms": ["покупа́ю"], "syntax_note": "vt" },
      { "lemma": "отдыха́ть", "translation": "休息", "pos": "verb", "forms": ["отдыха́ю"], "syntax_note": "" },
      { "lemma": "игра́ть", "translation": "玩，演奏", "pos": "verb", "forms": ["игра́ю"], "syntax_note": "+ в 4g (玩球) / + на 6g (乐器)" },
      { "lemma": "петь", "translation": "唱", "pos": "verb", "forms": ["пою́", "поёшь"], "syntax_note": "" },
      { "lemma": "танцева́ть", "translation": "跳舞", "pos": "verb", "forms": ["танцу́ю", "танцу́ешь"], "syntax_note": "-ева- 变 -у-" },
      { "lemma": "фотографи́роваться", "translation": "拍照/合影", "pos": "verb", "forms": ["-руюсь"], "syntax_note": "反身动词" },
      { "lemma": "вспомина́ть", "translation": "回忆起", "pos": "verb", "forms": ["вспомина́ю"], "syntax_note": "vt" },
      { "lemma": "собра́ться", "translation": "聚集，集合", "pos": "verb", "forms": ["собра́лся", "собрали́сь"], "syntax_note": "过去时常用" },
      { "lemma": "мечта́ть", "translation": "梦想", "pos": "verb", "forms": ["мечта́ю"], "syntax_note": "+ о 6g" },
      { "lemma": "ждать", "translation": "等待", "pos": "verb", "forms": ["жду", "ждёшь"], "syntax_note": "+ 2g/4g" },
      { "lemma": "роди́ться", "translation": "出生", "pos": "verb", "forms": ["роди́лся"], "syntax_note": "过去时" },
      { "lemma": "звать", "translation": "叫，称呼", "pos": "verb", "forms": ["зову́т"], "syntax_note": "Меня зовут..." }
    ]
  },
  {
    "category": "Nouns (People & Family) (名词：人、家庭、动物)",
    "items": [
      { "lemma": "семья́", "translation": "家庭", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "роди́тели", "translation": "父母", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "оте́ц", "translation": "父亲", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "мать", "translation": "母亲", "pos": "noun", "grammar": { "gender": "f", "special": "soft" } },
      { "lemma": "па́па", "translation": "爸爸", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ма́ма", "translation": "妈妈", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "де́душка", "translation": "爷爷/外公", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ба́бушка", "translation": "奶奶/外婆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дя́дя", "translation": "叔叔/舅舅", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тётя", "translation": "阿姨/姑姑", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "сын", "translation": "儿子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дочь", "translation": "女儿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "брат", "translation": "兄弟", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сестра́", "translation": "姐妹", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "де́ти", "translation": "孩子们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "челове́к", "translation": "人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "лю́ди", "translation": "人们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "мужчи́на", "translation": "男人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "же́нщина", "translation": "女人 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ма́льчик", "translation": "男孩", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "де́вушка", "translation": "姑娘", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "друг", "translation": "朋友", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "това́рищ", "translation": "同志/同学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сосе́д", "translation": "邻居 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гость", "translation": "客人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "преподава́тель", "translation": "大学教师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учи́тель", "translation": "中小学男老师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учи́тельница", "translation": "中小学女老师", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "студе́нт", "translation": "大学生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "шко́льник", "translation": "学生 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учени́к", "translation": "中小学生(男)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учени́ца", "translation": "中小学生(女)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "хи́мик", "translation": "化学家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "худо́жник", "translation": "画家/艺术家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "писа́тель", "translation": "作家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "врач", "translation": "医生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "космона́вт", "translation": "宇航员", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "шофёр", "translation": "司机", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "москви́ч", "translation": "莫斯科人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кот", "translation": "公猫", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "соба́ка", "translation": "狗", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "у́тка", "translation": "鸭子", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "по́вар", "translation": "厨师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "поэ́т", "translation": "诗人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "музыка́нт", "translation": "音乐家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "подру́га", "translation": "女朋友", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：(女性)朋友" },
      { "lemma": "гру́ппа", "translation": "班级/小组", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：组/班" }
    ]
  },
  {
    "category": "Nouns (Food & Drink) (名词：饮食)",
    "items": [
      { "lemma": "суп", "translation": "汤", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сок", "translation": "果汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "со́ус", "translation": "调味汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "у́ксус", "translation": "醋", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "са́хар", "translation": "糖", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "торт", "translation": "蛋糕", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "анана́с", "translation": "菠萝", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бана́н", "translation": "香蕉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "капу́ста", "translation": "白菜", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "тома́т", "translation": "番茄", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：番茄酱" }
    ]
  },
  {
    "category": "Nouns (Places & Objects) (名词：地点与物品)",
    "items": [
      { "lemma": "окно́", "translation": "窗户", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ка́сса", "translation": "收款台", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：售票处" },
      { "lemma": "мост", "translation": "桥", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "банк", "translation": "银行", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "заво́д", "translation": "工厂", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "重音在后" },
      { "lemma": "ры́нок", "translation": "市场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сад", "translation": "花园", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "复数：сады́ (重音后移)" },
      { "lemma": "вы́ставка", "translation": "展览/展览会", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "фонта́н", "translation": "喷泉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бар", "translation": "酒吧", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вход", "translation": "入口", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "反义词笔记：выход (出口)" },
      { "lemma": "кафе́", "translation": "咖啡馆", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：外来词，中性，不变格" },
      { "lemma": "фо́то", "translation": "照片", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：中性，不变化" },
      { "lemma": "су́мка", "translation": "手提包", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：书包" },
      { "lemma": "стака́н", "translation": "杯子/玻璃杯", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ва́за", "translation": "花瓶", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ко́фта", "translation": "女短上衣", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "университе́т", "translation": "大学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "институ́т", "translation": "学院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "шко́ла", "translation": "学校 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "библиоте́ка", "translation": "图书馆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "магази́н", "translation": "商店", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "столо́вая", "translation": "食堂", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ку́хня", "translation": "厨房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "буфе́т", "translation": "小卖部", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "теа́тр", "translation": "剧院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кинотеа́тр", "translation": "电影院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "музе́й", "translation": "博物馆", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "стадио́н", "translation": "体育场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "парк", "translation": "公园", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "больни́ца", "translation": "医院", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "санато́рий", "translation": "疗养院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "общежи́тие", "translation": "宿舍", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "кварти́ра", "translation": "公寓/套房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ко́мната", "translation": "房间", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дворе́ц", "translation": "宫殿", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "пло́щадь", "translation": "广场", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "у́лица", "translation": "街道", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "проспе́кт", "translation": "大街/大道", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дере́вня", "translation": "农村", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "метро́", "translation": "地铁", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "такси́", "translation": "出租车", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "авто́бус", "translation": "公交车", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "слова́рь", "translation": "字典", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тетра́дь", "translation": "练习本", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "уче́бник", "translation": "教科书", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "письмо́", "translation": "信", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "газе́та", "translation": "报纸", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "журна́л", "translation": "杂志", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "текст", "translation": "课文", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "упражне́ние", "translation": "练习/习题", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "сло́во", "translation": "单词", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "предложе́ние", "translation": "句子 (图外补充)", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "вопро́с", "translation": "问题", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "отве́т", "translation": "回答 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "экза́мен", "translation": "考试 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "де́ньги", "translation": "钱", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "рубль", "translation": "卢布", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "цветы́", "translation": "花", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "очки́", "translation": "眼镜", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "брю́ки", "translation": "裤子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "ту́фли", "translation": "鞋子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "о́бувь", "translation": "鞋类(总称)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "пальто́", "translation": "大衣", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "плащ", "translation": "风衣/雨衣", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гита́ра", "translation": "吉他", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ша́хматы", "translation": "象棋", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "мя́со", "translation": "肉", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ры́ба", "translation": "鱼 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "хлеб", "translation": "面包", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "молоко́", "translation": "牛奶", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "чай", "translation": "茶", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ко́фе", "translation": "咖啡", "pos": "noun", "grammar": { "gender": "m", "special": "indeclinable" } },
      { "lemma": "вода́", "translation": "水", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "сок", "translation": "果汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "пи́во", "translation": "啤酒", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "рис", "translation": "米饭", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "конфе́та", "translation": "糖果", "pos": "noun", "grammar": { "gender": "f" } }
    ]
  },
{
    "category": "Nouns(Body, Abstract & Nature) (身体、抽象与自然)",
    "items": [
      { "lemma": "нос", "translation": "鼻子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "нога́", "translation": "脚/腿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "рука́", "translation": "手", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "у́хо", "translation": "耳朵", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ум", "translation": "智慧/智力", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：聪明" },
      { "lemma": "сон", "translation": "梦", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：睡眠" },
      { "lemma": "рабо́та", "translation": "工作", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：作品/著作" },
      { "lemma": "спорт", "translation": "体育", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：运动" },
      { "lemma": "пого́да", "translation": "天气", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "гора́", "translation": "山", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ко́смос", "translation": "宇宙", "pos": "noun", "grammar": { "gender": "m" } }
    ]
  },
  {
    "category": "Adjectives (形容词)",
    "items": [
      { "lemma": "большо́й", "translation": "大的", "pos": "adj", "grammar": {} },
      { "lemma": "ма́ленький", "translation": "小的", "pos": "adj", "grammar": {} },
      { "lemma": "хоро́ший", "translation": "好的", "pos": "adj", "grammar": {} },
      { "lemma": "плохо́й", "translation": "坏的", "pos": "adj", "grammar": {} },
      { "lemma": "краси́вый", "translation": "美丽的", "pos": "adj", "grammar": {} },
      { "lemma": "интере́сный", "translation": "有趣的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "но́вый", "translation": "新的", "pos": "adj", "grammar": {} },
      { "lemma": "ста́рый", "translation": "旧的/老的", "pos": "adj", "grammar": {} },
      { "lemma": "молодо́й", "translation": "年轻的", "pos": "adj", "grammar": {} },
      { "lemma": "ста́рший", "translation": "年长的", "pos": "adj", "grammar": {} },
      { "lemma": "мла́дший", "translation": "年幼的", "pos": "adj", "grammar": {} },
      { "lemma": "до́брый", "translation": "善良的", "pos": "adj", "grammar": {} },
      { "lemma": "весёлый", "translation": "快乐的", "pos": "adj", "grammar": {} },
      { "lemma": "у́мный", "translation": "聪明的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "тру́дный", "translation": "困难的", "pos": "adj", "grammar": {} },
      { "lemma": "лёгкий", "translation": "容易的/轻的", "pos": "adj", "grammar": {} },
      { "lemma": "дорого́й", "translation": "贵的/亲爱的", "pos": "adj", "grammar": {} },
      { "lemma": "дешёвый", "translation": "便宜的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "горя́чий", "translation": "热的", "pos": "adj", "grammar": {} },
      { "lemma": "холо́дный", "translation": "冷的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "све́жий", "translation": "新鲜的", "pos": "adj", "grammar": {} },
      { "lemma": "чи́стый", "translation": "干净的", "pos": "adj", "grammar": {} },
      { "lemma": "кра́сный", "translation": "红色的", "pos": "adj", "grammar": {} },
      { "lemma": "си́ний", "translation": "蓝色的", "pos": "adj", "grammar": { "special": "soft" } },
      { "lemma": "бе́лый", "translation": "白色的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "чёрный", "translation": "黑色的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "ру́сский", "translation": "俄罗斯的", "pos": "adj", "grammar": {} },
      { "lemma": "кита́йский", "translation": "中国的", "pos": "adj", "grammar": {} },
      { "lemma": "англи́йский", "translation": "英国的", "pos": "adj", "grammar": {} },
      { "lemma": "пеки́нский", "translation": "北京的", "pos": "adj", "grammar": {} },
      { "lemma": "моско́вский", "translation": "莫斯科的", "pos": "adj", "grammar": {} },
      { "lemma": "дома́шний", "translation": "家庭的", "pos": "adj", "grammar": { "special": "soft" } }
    ]
  },
  {
    "category": "Adverbs & Others (副词、代词及其他)",
    "items": [
      { "lemma": "пока́", "translation": "暂时/当...时候", "pos": "adv", "grammar": {}, "syntax_note": "口语常用：回头见" },
      { "lemma": "опа́сно", "translation": "危险", "pos": "adv", "grammar": {} },
      { "lemma": "ра́но", "translation": "早", "pos": "adv", "grammar": {} },
      { "lemma": "су́хо", "translation": "干燥", "pos": "adv", "grammar": {} },
      { "lemma": "тут", "translation": "这里", "pos": "adv", "grammar": {}, "syntax_note": "口语常用" },
      { "lemma": "там", "translation": "那里", "pos": "adv", "grammar": {} },
      { "lemma": "пото́м", "translation": "然后", "pos": "adv", "grammar": {} },
      { "lemma": "поэ́тому", "translation": "所以/因此", "pos": "adv", "grammar": {} },
      { "lemma": "у", "translation": "在...旁边", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g (所有格)" },
      { "lemma": "от", "translation": "从.../由...", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g" },
      { "lemma": "стоп", "translation": "停", "pos": "other", "grammar": {}, "syntax_note": "图片手写补充" },
      { "lemma": "хорошо́", "translation": "好", "pos": "adv", "grammar": {} },
      { "lemma": "пло́хо", "translation": "坏/不好", "pos": "adv", "grammar": {} },
      { "lemma": "бы́стро", "translation": "快 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "ме́дленно", "translation": "慢 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "гро́мко", "translation": "大声地 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "ти́хо", "translation": "安静地", "pos": "adv", "grammar": {} },
      { "lemma": "вку́сно", "translation": "好吃", "pos": "adv", "grammar": {} },
      { "lemma": "интере́сно", "translation": "有趣", "pos": "adv", "grammar": {} },
      { "lemma": "сего́дня", "translation": "今天", "pos": "adv", "grammar": {} },
      { "lemma": "вчера́", "translation": "昨天", "pos": "adv", "grammar": {} },
      { "lemma": "за́втра", "translation": "明天", "pos": "adv", "grammar": {} },
      { "lemma": "сейча́с", "translation": "现在", "pos": "adv", "grammar": {} },
      { "lemma": "пото́м", "translation": "以后/随后", "pos": "adv", "grammar": {} },
      { "lemma": "ра́ньше", "translation": "以前", "pos": "adv", "grammar": {} },
      { "lemma": "давно́", "translation": "很久以前/许久", "pos": "adv", "grammar": {} },
      { "lemma": "неда́вно", "translation": "不久前", "pos": "adv", "grammar": {} },
      { "lemma": "здесь", "translation": "这里", "pos": "adv", "grammar": {} },
      { "lemma": "там", "translation": "那里 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "домо́й", "translation": "回家(去)", "pos": "adv", "grammar": {} },
      { "lemma": "до́ма", "translation": "在家 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "о́чень", "translation": "非常", "pos": "adv", "grammar": {} },
      { "lemma": "мно́го", "translation": "多", "pos": "adv", "grammar": {} },
      { "lemma": "ма́ло", "translation": "少 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "то́лько", "translation": "只/仅仅", "pos": "adv", "grammar": {} },
      { "lemma": "уже́", "translation": "已经", "pos": "adv", "grammar": {} },
      { "lemma": "ещё", "translation": "还/再", "pos": "adv", "grammar": {} },
      { "lemma": "то́же", "translation": "也", "pos": "adv", "grammar": {} },
      { "lemma": "почему́", "translation": "为什么", "pos": "adv", "grammar": {} },
      { "lemma": "потому́ что", "translation": "因为 (图外补充)", "pos": "pron", "grammar": {} },
      { "lemma": "кто", "translation": "谁", "pos": "pron", "grammar": {} },
      { "lemma": "что", "translation": "什么", "pos": "pron", "grammar": {} },
      { "lemma": "где", "translation": "在哪里", "pos": "adv", "grammar": {} },
      { "lemma": "куда́", "translation": "去哪里", "pos": "adv", "grammar": {} },
      { "lemma": "когда́", "translation": "什么时候", "pos": "adv", "grammar": {} },
      { "lemma": "как", "translation": "怎样", "pos": "adv", "grammar": {} },
      { "lemma": "ско́лько", "translation": "多少", "pos": "adv", "grammar": {} },
      { "lemma": "како́й", "translation": "什么样的", "pos": "pron", "grammar": {} },
      { "lemma": "чей", "translation": "谁的", "pos": "pron", "grammar": {} },
      { "lemma": "свой", "translation": "自己的", "pos": "pron", "grammar": {} },
      { "lemma": "спаси́бо", "translation": "谢谢", "pos": "other", "grammar": {} },
      { "lemma": "пожа́луйста", "translation": "请/不客气", "pos": "other", "grammar": {} },
      { "lemma": "приве́т", "translation": "你好(非正式)", "pos": "other", "grammar": {} },
      { "lemma": "здра́вствуйте", "translation": "您好(正式)", "pos": "other", "grammar": {} },
      { "lemma": "до свида́ния", "translation": "再见", "pos": "other", "grammar": {} }
    ]
  },
  {
    "category": "Numbers (数字)",
    "items": [
      { "lemma": "сто", "translation": "一百", "pos": "num", "grammar": {} },
      { "lemma": "оди́н", "translation": "一", "pos": "num", "grammar": {} },
      { "lemma": "два", "translation": "二", "pos": "num", "grammar": {} },
      { "lemma": "три", "translation": "三", "pos": "num", "grammar": {} },
      { "lemma": "четы́ре", "translation": "四", "pos": "num", "grammar": {} },
      { "lemma": "пять", "translation": "五", "pos": "num", "grammar": {} },
      { "lemma": "шесть", "translation": "六", "pos": "num", "grammar": {} },
      { "lemma": "семь", "translation": "七", "pos": "num", "grammar": {} },
      { "lemma": "во́семь", "translation": "八", "pos": "num", "grammar": {} },
      { "lemma": "де́вять", "translation": "九", "pos": "num", "grammar": {} },
      { "lemma": "де́сять", "translation": "十", "pos": "num", "grammar": {} },
      { "lemma": "оди́ннадцать", "translation": "十一", "pos": "num", "grammar": {} },
      { "lemma": "двена́дцать", "translation": "十二", "pos": "num", "grammar": {} }
    ]
  }
];