
import { Category, PartOfSpeech } from './types';

export const POS_LABELS: Record<PartOfSpeech, { label: string; color: string }> = {
  noun: { label: 'Noun', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  verb: { label: 'Verb', color: 'bg-red-100 text-red-800 border-red-200' },
  adj: { label: 'Adjective', color: 'bg-green-100 text-green-800 border-green-200' },
  adv: { label: 'Adverb', color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  pron: { label: 'Pronoun', color: 'bg-purple-100 text-purple-800 border-purple-200' },
  prep: { label: 'Preposition', color: 'bg-gray-100 text-gray-800 border-gray-200' },
  num: { label: 'Number', color: 'bg-indigo-100 text-indigo-800 border-indigo-200' },
  other: { label: 'Other', color: 'bg-teal-100 text-teal-800 border-teal-200' },
};

export const CONJUGATION_LABELS: Record<string, string> = {
  "1": "第一变位法 (e-变位)",
  "2": "第二变位法 (i-变位)",
  "mixed": "混合变位",
  "irregular": "特殊变位"
};

// --- PASTE YOUR JSON DATA BELOW ---
export const INITIAL_DATA: Category[] = [
  {
    "category": "Pronouns (代词)",
    "items": [
      { "lemma": "кто", "translation": "谁", "pos": "pron", "grammar": {} },
      { "lemma": "что", "translation": "什么", "pos": "pron", "grammar": {} },
      { "lemma": "како́й", "translation": "什么样的", "pos": "pron", "grammar": {} },
      { "lemma": "чей", "translation": "谁的", "pos": "pron", "grammar": {} },
      { "lemma": "я", "translation": "我", "pos": "pron", "grammar": {} },
      { "lemma": "ты", "translation": "你", "pos": "pron", "grammar": {} },
      { "lemma": "он", "translation": "他", "pos": "pron", "grammar": {} },
      { "lemma": "она́", "translation": "她", "pos": "pron", "grammar": {} },
      { "lemma": "оно́", "translation": "它", "pos": "pron", "grammar": {} },
      { "lemma": "мы", "translation": "我们", "pos": "pron", "grammar": {} },
      { "lemma": "вы", "translation": "你们/您", "pos": "pron", "grammar": {} },
      { "lemma": "они́", "translation": "他们", "pos": "pron", "grammar": {} },
      { "lemma": "себя́", "translation": "自己 (反身代词)", "pos": "pron", "grammar": {} },
      { "lemma": "мой", "translation": "我的", "pos": "pron", "grammar": {} },
      { "lemma": "твой", "translation": "你的", "pos": "pron", "grammar": {} },
      { "lemma": "наш", "translation": "我们的", "pos": "pron", "grammar": {} },
      { "lemma": "ваш", "translation": "你们的", "pos": "pron", "grammar": {} },
      { "lemma": "э́тот", "translation": "这个", "pos": "pron", "grammar": {} },
      { "lemma": "тот", "translation": "那个", "pos": "pron", "grammar": {} },
      { "lemma": "свой", "translation": "自己的", "pos": "pron", "grammar": {} },
      { "lemma": "тако́й", "translation": "这样的", "pos": "adj",  "grammar": { "gender": "m" }, "syntax_note": "指示代词/形容词" },
      { "lemma": "весь", "translation": "一切，全部，整个", "pos": "adj", "forms": ["вся", "всё", "все"], "grammar": { "gender": "m" },"syntax_note": "限定代词",},
    ]
  },
  {
    "category": "Time: Days, Months & Seasons (时间：星期/月份/季节)",
    "items": [
      { "lemma": "понеде́льник", "translation": "星期一", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вто́рник", "translation": "星期二", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "среда́", "translation": "星期三", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "четве́рг", "translation": "星期四", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "пя́тница", "translation": "星期五", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "суббо́та", "translation": "星期六", "pos": "noun", "grammar": { "gender": "f" }   },
      { "lemma": "воскресе́нье", "translation": "星期日", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "янва́рь", "translation": "一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "февра́ль", "translation": "二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "март", "translation": "三月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "апре́ль", "translation": "四月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "май", "translation": "五月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ию́нь", "translation": "六月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ию́ль", "translation": "七月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "а́вгуст", "translation": "八月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сентя́брь", "translation": "九月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "октя́брь", "translation": "十月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ноя́брь", "translation": "十一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дека́брь", "translation": "十二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "весна́", "translation": "春天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ле́то", "translation": "夏天", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "о́сень", "translation": "秋天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "зима́", "translation": "冬天", "pos": "noun", "grammar": { "gender": "f" } },

      { "lemma": "зимо́й", "translation": "在冬天", "pos": "adv", "grammar": {} },
      { "lemma": "весно́й", "translation": "在春天", "pos": "adv", "grammar": {} },
      { "lemma": "ле́том", "translation": "在夏天", "pos": "adv", "grammar": {}},
      { "lemma": "о́сенью", "translation": "在秋天", "pos": "adv", "grammar": {}},

      { "lemma": "вре́мя", "translation": "时间", "pos": "noun", "grammar": { "gender": "n", "special": "-мя" } },
      { "lemma": "календа́рь", "translation": "日历", "pos": "noun", "grammar": { "gender": "m" }   },
      { "lemma": "выходно́й", "translation": "休息日/假日", "pos": "noun", "grammar": { "gender": "m" }   },
      { "lemma": "у́тро", "translation": "早晨", "pos": "noun", "grammar": { "gender": "n" }   },
      { "lemma": "у́тром", "translation": "在早晨", "pos": "adv", "grammar": {}   },
      { "lemma": "позавчера́", "translation": "前天", "pos": "adv", "grammar": {}   },
      { "lemma": "сего́дня", "translation": "今天", "pos": "adv", "grammar": {} },
      { "lemma": "тепе́рь", "translation": "现在 (与сейчас有细微区别)", "pos": "adv", "grammar": {}   },
      { "lemma": "сейчас", "translation": "现在", "pos": "adv", "grammar": {}   },
      { "lemma": "ве́чером", "translation": "在晚上", "pos": "adv", "grammar": {}   },
      { "lemma": "но́чью", "translation": "在夜里", "pos": "adv", "grammar": {}   },
      { "lemma": "день", "translation": "白天/日子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ве́чер", "translation": "晚上", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ночь", "translation": "夜里", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "час", "translation": "小时/时刻", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "мину́та", "translation": "分钟", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "год", "translation": "年", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ме́сяц", "translation": "月(时间单位)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "неде́ля", "translation": "周/星期(时间单位)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "за́втра", "translation": "明天", "pos": "adv", "grammar": {} },
      { "lemma": "сейча́с", "translation": "现在", "pos": "adv", "grammar": {} },
      { "lemma": "пото́м", "translation": "然后", "pos": "adv", "grammar": {} },
      { "lemma": "ра́ньше", "translation": "以前", "pos": "adv", "grammar": {} },
      { "lemma": "давно́", "translation": "很久以前/许久", "pos": "adv", "grammar": {} },
      { "lemma": "неда́вно", "translation": "不久前", "pos": "adv", "grammar": {} }
    ]
  },
  {
    "category": "Verbs (核心动词)",
    "items": [
      { "lemma": "быть", "translation": "是/存在", "pos": "verb", "forms": ["есть (现)", "бу́ду (将)", "бу́дешь"], "grammar": { "conjugation": "irregular" }, "syntax_note": "现在时通常省略或用есть" },
      { "lemma": "встава́ть", "translation": "起床", "pos": "verb", "forms": ["встаю́", "встаёшь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "вспомина́ть", "translation": "回忆起", "pos": "verb", "forms": ["вспомина́ю", "вспомина́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vt" },
      { "lemma": "ви́деть", "translation": "看见", "pos": "verb", "forms": ["ви́жу", "ви́дишь", "ви́дят"], "grammar": { "conjugation": "2" }, "syntax_note": "vt" },
      { "lemma": "гуля́ть", "translation": "散步", "pos": "verb", "forms": ["гуля́ю", "гуля́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vi + 6g (在...散步)" },
      { "lemma": "говори́ть", "translation": "说", "pos": "verb", "forms": ["говорю́", "говори́шь"], "grammar": { "conjugation": "2" }, "syntax_note": "vi/vt" },
      { "lemma": "де́лать", "translation": "做", "pos": "verb", "forms": ["де́лаю", "де́лаешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "е́хать", "translation": "乘车去", "pos": "verb", "forms": ["е́ду", "е́дешь"], "grammar": { "conjugation": "1" }, "syntax_note": "Motion" },
      { "lemma": "есть", "translation": "吃", "pos": "verb", "forms": ["ем", "ешь", "едят"], "grammar": { "conjugation": "irregular" }, "syntax_note": "" },
      { "lemma": "жить", "translation": "生活/居住", "pos": "verb", "forms": ["живу́", "живёшь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "ждать", "translation": "等待", "pos": "verb", "forms": ["жду", "ждёшь"], "grammar": { "conjugation": "1" }, "syntax_note": "+ 2g/4g" },
      { "lemma": "знать", "translation": "知道/了解", "pos": "verb", "forms": ["зна́ю", "зна́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "занима́ться", "translation": "从事，做功课", "pos": "verb", "forms": ["занима́юсь", "занима́ешься"], "grammar": { "conjugation": "1" }, "syntax_note": "vi + 5g" },
      { "lemma": "за́втракать", "translation": "吃早饭", "pos": "verb", "forms": ["за́втракаю", "за́втракаешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "звать", "translation": "叫，称呼", "pos": "verb", "forms": ["зову́", "зовёшь", "зову́т"], "grammar": { "conjugation": "1" }, "syntax_note": "Меня зовут..." },
      { "lemma": "игра́ть", "translation": "玩，演奏", "pos": "verb", "forms": ["игра́ю", "игра́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "+ в 4g (玩球) / + на 6g (乐器)" },
      { "lemma": "идти́", "translation": "走 (正在进行)", "pos": "verb", "forms": ["иду́", "идёшь"], "grammar": { "conjugation": "1" }, "syntax_note": "Motion" },
      { "lemma": "изуча́ть", "translation": "研究，钻研", "pos": "verb", "forms": ["изуча́ю", "изуча́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vt + 4g" },
      { "lemma": "лежа́ть", "translation": "平放，躺", "pos": "verb", "forms": ["лежу́", "лежи́шь"], "grammar": { "conjugation": "2" }, "syntax_note": "vi + 6g" },
      { "lemma": "лете́ть", "translation": "飞", "pos": "verb", "forms": ["лечу́", "лети́шь"], "grammar": { "conjugation": "2" }, "syntax_note": "Motion" },
      { "lemma": "люби́ть", "translation": "爱", "pos": "verb", "forms": ["люблю́", "лю́бишь"], "grammar": { "conjugation": "2" }, "syntax_note": "+ vt / n." },
      { "lemma": "мечта́ть", "translation": "梦想", "pos": "verb", "forms": ["мечта́ю", "мечта́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "+ о 6g" },
      { "lemma": "обе́дать", "translation": "吃午饭", "pos": "verb", "forms": ["обе́даю", "обе́даешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "отвеча́ть", "translation": "回答", "pos": "verb", "forms": ["отвеча́ю", "отвеча́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "отдыха́ть", "translation": "休息", "pos": "verb", "forms": ["отдыха́ю", "отдыха́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "писа́ть", "translation": "写", "pos": "verb", "forms": ["пишу́", "пи́шешь"], "grammar": { "conjugation": "1" }, "syntax_note": "с-ш 音变" },
      { "lemma": "покупа́ть", "translation": "购买", "pos": "verb", "forms": ["покупа́ю", "покупа́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vt" },
      { "lemma": "петь", "translation": "唱", "pos": "verb", "forms": ["пою́", "поёшь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "разгова́ривать", "translation": "交谈", "pos": "verb", "forms": ["разгова́риваю", "разгова́риваешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "расска́зывать", "translation": "讲述，讲故事", "pos": "verb", "forms": ["расска́зываю", "расска́зываешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vt. (+ о 6g)" },
      { "lemma": "рабо́тать", "translation": "工作", "pos": "verb", "forms": ["рабо́таю", "рабо́таешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "роди́ться", "translation": "出生", "pos": "verb", "forms": ["роди́лся", "родила́сь"], "grammar": { "conjugation": "2" }, "syntax_note": "常用过去时" },
      { "lemma": "сказа́ть", "translation": "说 (完成体)", "pos": "verb", "forms": ["скажу́", "ска́жешь"], "grammar": { "conjugation": "1" }, "syntax_note": "命令式: скажи́" },
      { "lemma": "смотре́ть", "translation": "看 (观看)", "pos": "verb", "forms": ["смотрю́", "смо́тришь"], "grammar": { "conjugation": "2" }, "syntax_note": "vt" },
      { "lemma": "слу́шать", "translation": "听", "pos": "verb", "forms": ["слу́шаю", "слу́шаешь"], "grammar": { "conjugation": "1" }, "syntax_note": "vt" },
      { "lemma": "слы́шать", "translation": "听见", "pos": "verb", "forms": ["слышу", "слышишь", "слышат"], "syntax_note": "(图外补充，常与слушать对比), (II)" },
      { "lemma": "стоя́ть", "translation": "站立", "pos": "verb", "forms": ["стою́", "стои́шь"], "grammar": { "conjugation": "2" }, "syntax_note": "vi + 6g" },
      { "lemma": "сиде́ть", "translation": "坐", "pos": "verb", "forms": ["сижу́", "сиди́шь"], "grammar": { "conjugation": "2" }, "syntax_note": "vi" },
      { "lemma": "собра́ться", "translation": "聚集，集合", "pos": "verb", "forms": ["собра́лся", "собрали́сь"], "grammar": { "conjugation": "1" }, "syntax_note": "常用过去时" },
      { "lemma": "счита́ть", "translation": "数数/计算", "pos": "verb", "forms": ["счита́ю", "счита́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "учи́ться", "translation": "学习 (在某处)", "pos": "verb", "forms": ["учу́сь", "у́чишься", "у́чатся"], "grammar": { "conjugation": "2" }, "syntax_note": "vi + 6g (在...)" },
      { "lemma": "учи́ть", "translation": "学习 (背诵/教授)", "pos": "verb", "forms": ["учу́", "у́чишь"], "grammar": { "conjugation": "2" }, "syntax_note": "vt + 4g (学什么)" },
      { "lemma": "у́жинать", "translation": "吃晚饭", "pos": "verb", "forms": ["у́жинаю", "у́жинаешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" },
      { "lemma": "фотографи́роваться", "translation": "拍照/合影", "pos": "verb", "forms": ["фотографи́руюсь", "фотографи́руешься"], "grammar": { "conjugation": "1" }, "syntax_note": "反身动词" },
      { "lemma": "хоте́ть", "translation": "想要", "pos": "verb", "forms": ["хочу́", "хо́чешь", "хотя́т"], "grammar": { "conjugation": "mixed" }, "syntax_note": "混合变位" },
      { "lemma": "чита́ть", "translation": "读/阅读", "pos": "verb", "forms": ["чита́ю", "чита́ешь"], "grammar": { "conjugation": "1" }, "syntax_note": "" }
    ]
  },
  {
    "category": "Nouns (People & Family) (名词：人、家庭)",
    "items": [
      { "lemma": "преподава́тельница", "translation": "大学女老师", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：(中、高等学校)教师，教员" },
      { "lemma": "студе́нтка", "translation": "女大学生", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "москви́чка", "translation": "莫斯科人(女)", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "го́стья", "translation": "女客人", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "до́чка", "translation": "女儿 (爱称)", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "чемпио́н", "translation": "冠军", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "ребя́та", "translation": "伙计们；孩子们", "pos": "noun", "grammar": { "plural_only": true }, "syntax_note": "笔记补充：小伙子们；同学们" },
      { "lemma": "семья́", "translation": "家庭", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "роди́тели", "translation": "父母", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "оте́ц", "translation": "父亲", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "мать", "translation": "母亲", "pos": "noun", "grammar": { "gender": "f", "special": "soft" } },
      { "lemma": "па́па", "translation": "爸爸", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ма́ма", "translation": "妈妈", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "де́душка", "translation": "爷爷/外公", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ба́бушка", "translation": "奶奶/外婆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дя́дя", "translation": "叔叔/舅舅", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тётя", "translation": "阿姨/姑姑", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "сын", "translation": "儿子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дочь", "translation": "女儿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "брат", "translation": "兄弟", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сестра́", "translation": "姐妹", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "де́ти", "translation": "孩子们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "челове́к", "translation": "人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "лю́ди", "translation": "人们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "ма́льчик", "translation": "男孩", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "де́вушка", "translation": "姑娘", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "друг", "translation": "朋友", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "това́рищ", "translation": "同志/同学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гость", "translation": "客人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "преподава́тель", "translation": "大学教师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учи́тель", "translation": "中小学男老师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учи́тельница", "translation": "中小学女老师", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "студе́нт", "translation": "大学生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учени́к", "translation": "中小学生(男)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учени́ца", "translation": "中小学生(女)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "хи́мик", "translation": "化学家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "худо́жник", "translation": "画家/艺术家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "писа́тель", "translation": "作家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "врач", "translation": "医生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "космона́вт", "translation": "宇航员", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "шофёр", "translation": "司机", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "москви́ч", "translation": "莫斯科人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "по́вар", "translation": "厨师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "поэ́т", "translation": "诗人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "музыка́нт", "translation": "音乐家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "подру́га", "translation": "女朋友", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：(女性)朋友" },
      { "lemma": "гру́ппа", "translation": "班级/小组", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：组/班" },
      { "lemma": "муж", "translation": "丈夫", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "жена́", "translation": "妻子", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "инжене́р", "translation": "工程师", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" }
    ]
  },
  {
    "category": "Nouns (Food & Drink) (名词：饮食、动物)",
    "items": [
      { "lemma": "сала́т", "translation": "沙拉", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "гру́ша", "translation": "梨", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "карто́шка", "translation": "土豆", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "у́жин", "translation": "晚饭", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      {"lemma": "хлеб","translation": "面包","pos": "noun","grammar": { "gender": "m" }},
      { "lemma": "молоко́", "translation": "牛奶", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ко́фе", "translation": "咖啡", "pos": "noun", "grammar": { "gender": "m", "special": "indeclinable" } },
      {"lemma": "мя́со","translation": "肉","pos": "noun","grammar": { "gender": "n" }},
      {"lemma": "чай","translation": "茶","pos": "noun","grammar": { "gender": "m" }},
      {"lemma": "о́вощи","translation": "蔬菜","pos": "noun","grammar": { "plural_only": true},"syntax_note": "图片标注 [复]" },
      {"lemma": "вода́","translation": "水; 饮料; 水域","pos": "noun","grammar": { "gender": "f" },"syntax_note": "plural_form: во́ды"},
      {"lemma": "рис","translation": "米饭,大米","pos": "noun","grammar": { "gender": "m" }},
      {"lemma": "пи́во","translation": "啤酒","pos": "noun","grammar": { "gender": "n" }},
      {"lemma": "конфе́та","translation": "糖果","pos": "noun","grammar": { "gender": "f" }},
      {"lemma": "обе́д","translation": "午饭","pos": "noun","grammar": { "gender": "m" }},
      {"lemma": "за́втрак", "translation": "早餐", "pos": "noun", "grammar": { "gender": "m" }},
      { "lemma": "суп", "translation": "汤", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сок", "translation": "果汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "со́ус", "translation": "调味汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "у́ксус", "translation": "醋", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "са́хар", "translation": "糖", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "торт", "translation": "蛋糕", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "анана́с", "translation": "菠萝", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бана́н", "translation": "香蕉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "капу́ста", "translation": "白菜", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "тома́т", "translation": "番茄", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：番茄酱" },
      { "lemma": "я́блоко", "translation": "苹果", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "яйцо́", "translation": "鸡蛋", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "кот", "translation": "公猫", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "соба́ка", "translation": "狗", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "у́тка", "translation": "鸭子", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ко́шка", "translation": "猫，母猫", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" }
    ]
  },
  {
    "category": "Nouns (Places) (名词：地点)",
    "items": [
      { "lemma": "магази́н", "translation": "商店", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "библиоте́ка", "translation": "图书馆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "по́ле", "translation": "田野；场地", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": "图片标注：(中)" },
      { "lemma": "стадио́н", "translation": "体育场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "у́лица", "translation": "街道", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "метро́", "translation": "地铁", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "ку́хня", "translation": "厨房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "кино́", "translation": "影院；电影", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "图片标注：不变" },
      { "lemma": "Росси́я", "translation": "俄罗斯", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "А́зия", "translation": "亚洲", "pos": "noun", "grammar": { "gender": "f" },  "syntax_note": "" },
      { "lemma": "Ки́ев", "translation": "基辅", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      {"lemma": "Пеки́н", "translation": "北京", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      {"lemma": "Кита́й","translation": "中国","pos": "noun","grammar": { "gender": "m" },"syntax_note": ""},
      {"lemma": "парк","translation": "公园","pos": "noun","grammar": { "gender": "m" },"syntax_note": "笔记补充：场，库 (停车场)"},
      {"lemma": "кремль","translation": "(古俄罗斯城堡的)内墙","pos": "noun","grammar": { "gender": "m" },"syntax_note": "笔记补充：(克里姆林宫)"},
      { "lemma": "пло́щадь", "translation": "广场", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "теа́тр", "translation": "剧院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "институ́т", "translation": "学院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "общежи́тие", "translation": "宿舍", "pos": "noun", "grammar": { "gender": "n" } },
      {"lemma": "по́чта","translation": "邮局；邮件","pos": "noun","grammar": { "gender": "f" },"syntax_note": ""},
      {"lemma": "юг","translation": "南方，南","pos": "noun","grammar": { "gender": "m" },"syntax_note": "na"},
      { "lemma": "университе́т", "translation": "大学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "столо́вая", "translation": "餐厅；食堂", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дере́вня", "translation": "农村", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "кварти́ра", "translation": "公寓/套房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дворе́ц", "translation": "宫殿", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кинотеа́тр", "translation": "电影院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "больни́ца", "translation": "医院", "pos": "noun", "grammar": { "gender": "f" } },
      {"lemma": "ме́сто","translation": "地方；座位","pos": "noun", "grammar": { "gender": "n" },"syntax_note": "语法补充：复-а"},
      {"lemma": "а́дрес","translation": "地址","pos": "noun","grammar": { "gender": "m" },"syntax_note": "语法补充：复-а (重音后移)" },
      { "lemma": "мо́ре", "translation": "海", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "река́", "translation": "河", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "проспе́кт", "translation": "大街/大道", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "буфе́т", "translation": "小卖部", "pos": "noun", "grammar": { "gender": "m" } },
      {"lemma": "аудито́рия","translation": "(大学)教室","pos": "noun","grammar": { "gender": "f" },"syntax_note": ""},
      { "lemma": "санато́рий", "translation": "疗养院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дом", "translation": "房子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вы́ставка", "translation": "展览/展览会", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "банк", "translation": "银行", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сад", "translation": "花园", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "复数：сады́ (重音后移)" },
      { "lemma": "фонта́н", "translation": "喷泉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кафе́", "translation": "咖啡馆", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：外来词，中性，不变格" },
      {"lemma": "вуз", "translation": "高等学校","pos": "noun","grammar": { "gender": "m" },"syntax_note": ""},
      { "lemma": "заво́д", "translation": "工厂", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "重音在后" },
      { "lemma": "гора́", "translation": "山", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "го́род", "translation": "城市", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бар", "translation": "酒吧", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ры́нок", "translation": "市场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вход", "translation": "入口", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "反义词笔记：выход (出口)" },
      { "lemma": "окно́", "translation": "窗户", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "мост", "translation": "桥", "pos": "noun", "grammar": { "gender": "m" } },
      {"lemma": "ка́сса","translation": "收款台；售票处","pos": "noun","grammar": { "gender": "f" }},
      { "lemma": "музе́й", "translation": "博物馆", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ко́мната", "translation": "房间", "pos": "noun", "grammar": { "gender": "f" } },
      {"lemma": "ко́смос","translation": "宇宙","pos": "noun","grammar": { "gender": "m" },"syntax_note": ""},
      { "lemma": "класс", "translation": "(中小学的)班；年级", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：阶级；等级" },
      { "lemma": "конце́рт", "translation": "音乐会", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "вокза́л", "translation": "火车站", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "цех", "translation": "车间", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "центр", "translation": "中心", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "цирк", "translation": "杂技；马戏", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：马戏" },
      { "lemma": "сайт", "translation": "网站", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "по́езд", "translation": "火车", "pos": "noun", "grammar": { "gender": "m"}, "syntax_note": "plural_form: -а" },
      { "lemma": "шко́ла", "translation": "中，小学校", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：中，小学校" },
      { "lemma": "Евро́па", "translation": "欧洲", "pos": "noun", "grammar": { "gender": "f"}, "syntax_note": "*专有名词" },
      { "lemma": "Шанха́й", "translation": "上海", "pos": "noun", "grammar": { "gender": "m"}, "syntax_note": "" }
    ]
  },
  {
    "category": "Nouns (Objects) (名词：物品)",
    "items": [
      { "lemma": "ла́мпа", "translation": "灯", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "стол", "translation": "桌子", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "plural_form: -ы" },
      { "lemma": "стул", "translation": "椅子", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "ло́дка", "translation": "船", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "по́лка", "translation": "书架", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "шкаф", "translation": "柜子", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "ша́пка", "translation": "帽子", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "маши́на", "translation": "机器，汽车", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "ёлка", "translation": "新年枞树", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "нож", "translation": "刀子", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "фо́то", "translation": "照片", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：中性，不变化" },
      { "lemma": "су́мка", "translation": "手提包", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：书包" },
      { "lemma": "стака́н", "translation": "杯子/玻璃杯", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "рюмка", "translation": "高脚酒杯", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ча́шка", "translation": "马克杯（带把手ручка），用于装чай, кофе", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "таре́лка", "translation": "盘子，用于装мясо, курица", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ва́за", "translation": "花瓶", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ко́фта", "translation": "女短上衣", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "такси́", "translation": "出租车", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "авто́бус", "translation": "公交车", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "слова́рь", "translation": "字典", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тетра́дь", "translation": "练习本", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "уче́бник", "translation": "教科书", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "письмо́", "translation": "信", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "газе́та", "translation": "报纸", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "журна́л", "translation": "杂志", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "текст", "translation": "课文", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "упражне́ние", "translation": "练习/习题", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "сло́во", "translation": "单词", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "вопро́с", "translation": "问题", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "де́ньги", "translation": "钱", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "рубль", "translation": "卢布", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "цветы́", "translation": "花", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "очки́", "translation": "眼镜", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "брю́ки", "translation": "裤子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "ту́фли", "translation": "鞋子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "о́бувь", "translation": "鞋类(总称)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "пальто́", "translation": "大衣", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "плащ", "translation": "风衣/雨衣", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гита́ра", "translation": "吉他", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ша́хматы", "translation": "象棋", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "кни́га", "translation": "书", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ру́чка", "translation": "钢笔/笔", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "бу́ква", "translation": "字母", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "уро́к", "translation": "功课/课", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "зада́ние", "translation": "作业/任务", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "сочине́ние", "translation": "作文", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "му́зыка", "translation": "音乐", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "пе́сня", "translation": "歌曲", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "стихи́", "translation": "诗歌 (复数)", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "па́спорт", "translation": "护照", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "телеви́зор", "translation": "电视机", "pos": "noun", "grammar": { "gender": "m" }},
      { "lemma": "ра́дио", "translation": "收音机/广播", "pos": "noun", "grammar": { "gender": "n" }},
      { "lemma": "часы́", "translation": "钟表/手表", "pos": "noun", "grammar": { "plural_only": true }},
      { "lemma": "футбо́л", "translation": "足球", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "сло́во", "translation": "单词", "pos": "noun", "grammar": { "gender": "n"}, "syntax_note": "" },
      { "lemma": "цена́", "translation": "价格", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "компью́тер", "translation": "电脑", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "телефо́н", "translation": "电话", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "фильм", "translation": "影片", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "рю́мка", "translation": "高脚酒杯", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" }
    ]
  },
  {
    "category": "Nouns(Body, Abstract & Nature) (身体、抽象与自然)",
    "items": [
      { "lemma": "нос", "translation": "鼻子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "нога́", "translation": "脚/腿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "рука́", "translation": "手", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "у́хо", "translation": "耳朵", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ум", "translation": "智慧/智力", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：聪明" },
      { "lemma": "сон", "translation": "梦", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：睡眠" },
      { "lemma": "рабо́та", "translation": "工作", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：作品/著作" },
      { "lemma": "спорт", "translation": "体育", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：运动" },
      { "lemma": "пого́да", "translation": "天气", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "де́рево", "translation": "树", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "о́зеро", "translation": "湖", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": ""},
      { "lemma": "снег", "translation": "雪", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "фи́рма", "translation": "公司", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "ле́кция", "translation": "(大学的)讲课，讲座", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "заня́тие", "translation": "课，课堂", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": "" },
      { "lemma": "специа́льность", "translation": "专业", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "图片标注：[阴]" },
      { "lemma": "литерату́ра", "translation": "文学", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "видеофи́льм", "translation": "影视剧", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "расска́з", "translation": "讲述；故事；短篇小说", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "язы́к", "translation": "语言；舌头", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "сча́стье", "translation": "幸福", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": "" },
      { "lemma": "мир", "translation": "和平；世界", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "" },
      { "lemma": "и́мя", "translation": "名字", "pos": "noun", "grammar": { "gender": "n", "special": "-мя" }, "syntax_note": "" },
      { "lemma": "собра́ние", "translation": "会议", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": "图片标注：(中)" },
      { "lemma": "Интерне́т", "translation": "因特网", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "注音：[тэрнэ]" },
      { "lemma": "хи́мия", "translation": "化学", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "" },
      { "lemma": "жизнь", "translation": "生活；生命", "pos": "noun", "grammar": { "gender": "f", "special": "soft" }, "syntax_note": "", },
      { "lemma": "де́тство", "translation": "童年", "pos": "noun", "grammar": { "gender": "n" }, "syntax_note": "", },
      { "lemma": "переры́в", "translation": "休息 (课间/工间)", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "", },
      { "lemma": "матема́тика", "translation": "数学", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "", },
    ]
  },
  {
    "category": "Adjectives (形容词)",
    "items": [
      { "lemma": "шко́льный", "translation": "中小学的", "pos": "adj","grammar": { "gender": "m" },"syntax_note": ""},
      { "lemma": "зи́мний", "translation": "冬天的；冬季用的","pos": "adj","grammar": { "gender": "m", "special": "soft" },"syntax_note": ""},
      {"lemma": "лё́тний", "translation": "夏天的","pos": "adj","grammar": { "gender": "m", "special": "soft" },"syntax_note": ""},
      {"lemma": "торго́вый","translation": "贸易的","pos": "adj","grammar": { "gender": "m" },"syntax_note": ""},
      { "lemma": "истори́ческий", "translation": "历史的", "pos": "adj", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：(历史上的)"},
      { "lemma": "ка́ждый","translation": "每个，每","pos": "adj","grammar": { "gender": "m" },"syntax_note": "代词性形容词"},
      {"lemma": "родно́й","translation": "家乡的；亲爱的","pos": "adj","grammar": { "gender": "m" },"syntax_note": ""},
      {"lemma": "знамени́тый","translation": "著名的","pos": "adj","grammar": { "gender": "m" },"syntax_note": ""},
      { "lemma": "рабо́чий", "translation": "工人的/工作的", "pos": "adj", "grammar": {} },
      { "lemma": "вече́рний", "translation": "晚上的", "pos": "adj", "grammar": {} },
      { "lemma": "сре́дний", "translation": "中间的/中等的", "pos": "adj", "grammar": {} },
      { "lemma": "медици́нский", "translation": "医学的", "pos": "adj", "grammar": {} },
      { "lemma": "педагоги́ческий", "translation": "师范的", "pos": "adj", "grammar": {} },
      { "lemma": "городско́й", "translation": "城市的", "pos": "adj", "grammar": {} },
      { "lemma": "де́тский", "translation": "儿童的", "pos": "adj", "grammar": {} },
      { "lemma": "вели́кий", "translation": "伟大的", "pos": "adj", "grammar": {} },
      { "lemma": "больно́й", "translation": "有病的/病人", "pos": "adj", "grammar": {} },
      { "lemma": "большо́й", "translation": "大的", "pos": "adj", "grammar": {} },
      { "lemma": "ма́ленький", "translation": "小的", "pos": "adj", "grammar": {} },
      { "lemma": "хоро́ший", "translation": "好的", "pos": "adj", "grammar": {} },
      { "lemma": "плохо́й", "translation": "坏的", "pos": "adj", "grammar": {} },
      { "lemma": "краси́вый", "translation": "美丽的", "pos": "adj", "grammar": {} },
      { "lemma": "но́вый", "translation": "新的", "pos": "adj", "grammar": {} },
      { "lemma": "ста́рый", "translation": "旧的/老的", "pos": "adj", "grammar": {} },
      { "lemma": "молодо́й", "translation": "年轻的", "pos": "adj", "grammar": {} },
      { "lemma": "ста́рший", "translation": "年长的", "pos": "adj", "grammar": {} },
      { "lemma": "мла́дший", "translation": "年幼的", "pos": "adj", "grammar": {} },
      { "lemma": "до́брый", "translation": "善良的", "pos": "adj", "grammar": {} },
      { "lemma": "весёлый", "translation": "快乐的", "pos": "adj", "grammar": {} },
      { "lemma": "горя́чий", "translation": "热的", "pos": "adj", "grammar": {} },
      { "lemma": "све́жий", "translation": "新鲜的", "pos": "adj", "grammar": {} },
      { "lemma": "кра́сный", "translation": "红色的", "pos": "adj", "grammar": {} },
      { "lemma": "си́ний", "translation": "蓝色的", "pos": "adj", "grammar": { "special": "soft" } },
      { "lemma": "ру́сский", "translation": "俄罗斯的", "pos": "adj", "grammar": {} },
      { "lemma": "кита́йский", "translation": "中国的", "pos": "adj", "grammar": {} },
      { "lemma": "англи́йский", "translation": "英国的", "pos": "adj", "grammar": {} },
      { "lemma": "пеки́нский", "translation": "北京的", "pos": "adj", "grammar": {} },
      { "lemma": "моско́вский", "translation": "莫斯科的", "pos": "adj", "grammar": {} },
      { "lemma": "дома́шний", "translation": "家庭的", "pos": "adj", "grammar": { "special": "soft" } }
    ]
  },
  {
    "category": "Adverbs & Others (副词、代词及其他)",
    "items": [
      {  "lemma": "темно́", "translation": "黑暗", "pos": "adv", "grammar": {}  },
      { "lemma": "чи́сто", "translation": "干净地", "pos": "adv", "grammar": {} },
      { "lemma": "так", "translation": "这样/如此", "pos": "adv", "grammar": {} },
      { "lemma": "потому́", "translation": "因此 (常接что)", "pos": "adv", "grammar": {} },
      { "lemma": "обы́чно", "translation": "通常", "pos": "adv", "grammar": {} },
      { "lemma": "вме́сте", "translation": "一起", "pos": "adv", "grammar": {} },
      { "lemma": "здо́рово", "translation": "太棒了/真好", "pos": "adv", "grammar": {} },
      { "lemma": "по-кита́йски", "translation": "用汉语/汉语地", "pos": "adv", "grammar": {} },
      { "lemma": "по-ру́сски", "translation": "用俄语/俄语地", "pos": "adv", "grammar": {} },
      { "lemma": "пока́", "translation": "暂时/当...时候", "pos": "adv", "grammar": {}, "syntax_note": "口语常用：回头见" },
      { "lemma": "опа́сно", "translation": "危险", "pos": "adv", "grammar": {} },
      { "lemma": "ра́но", "translation": "早", "pos": "adv", "grammar": {} },
      { "lemma": "су́хо", "translation": "干燥", "pos": "adv", "grammar": {} },
      { "lemma": "тут", "translation": "这里", "pos": "adv", "grammar": {}, "syntax_note": "口语常用" },
      { "lemma": "там", "translation": "那里", "pos": "adv", "grammar": {} },
      { "lemma": "поэ́тому", "translation": "所以/因此", "pos": "adv", "grammar": {} },
      { "lemma": "стоп", "translation": "停", "pos": "other", "grammar": {}, "syntax_note": "图片手写补充" },
      { "lemma": "хорошо́", "translation": "好", "pos": "adv", "grammar": {} },
      { "lemma": "пло́хо", "translation": "坏/不好", "pos": "adv", "grammar": {} },
      { "lemma": "ти́хо", "translation": "安静地", "pos": "adv", "grammar": {} },
      { "lemma": "вку́сно", "translation": "好吃", "pos": "adv", "grammar": {} },
      { "lemma": "интере́сно", "translation": "有趣", "pos": "adv", "grammar": {} },
      { "lemma": "здесь", "translation": "这里", "pos": "adv", "grammar": {} },
      { "lemma": "там", "translation": "那里", "pos": "adv", "grammar": {} },
      { "lemma": "домо́й", "translation": "回家(去)", "pos": "adv", "grammar": {} },
      { "lemma": "до́ма", "translation": "在家", "pos": "adv", "grammar": {} },
      { "lemma": "о́чень", "translation": "非常", "pos": "adv", "grammar": {} },
      { "lemma": "мно́го", "translation": "多", "pos": "adv", "grammar": {} },
      { "lemma": "то́лько", "translation": "只/仅仅", "pos": "adv", "grammar": {} },
      { "lemma": "уже́", "translation": "已经", "pos": "adv", "grammar": {} },
      { "lemma": "ещё", "translation": "还/再", "pos": "adv", "grammar": {} },
      { "lemma": "то́же", "translation": "也", "pos": "adv", "grammar": {} },
      { "lemma": "почему́", "translation": "为什么", "pos": "adv", "grammar": {} },
      { "lemma": "где", "translation": "在哪里", "pos": "adv", "grammar": {} },
      { "lemma": "куда́", "translation": "去哪里", "pos": "adv", "grammar": {} },
      { "lemma": "когда́", "translation": "什么时候", "pos": "adv", "grammar": {} },
      { "lemma": "как", "translation": "怎样", "pos": "adv", "grammar": {} },
      { "lemma": "ско́лько", "translation": "多少", "pos": "adv", "grammar": {} },
      { "lemma": "спаси́бо", "translation": "谢谢", "pos": "other", "grammar": {} },
      { "lemma": "пожа́луйста", "translation": "请/不客气", "pos": "other", "grammar": {} },
      { "lemma": "приве́т", "translation": "你好(非正式)", "pos": "other", "grammar": {} },
      { "lemma": "здра́вствуйте", "translation": "您好(正式)", "pos": "other", "grammar": {} },
      { "lemma": "до свида́ния", "translation": "再见", "pos": "other", "grammar": {} },
      { "lemma": "здра́вствуй(-те)", "translation": "你(您)好", "pos": "other", "grammar": { }, "syntax_note": "[命令式]" },
      { "lemma": "то́же", "translation": "也", "pos": "adv", "grammar": {}, "syntax_note": "" }
    ]
  },
  {
    "category": "Numbers (数字)",
    "items": [
      { "lemma": "сто", "translation": "一百", "pos": "num", "grammar": {} },
      { "lemma": "оди́н", "translation": "一", "pos": "num", "grammar": {} },
      { "lemma": "два", "translation": "二", "pos": "num", "grammar": {} },
      { "lemma": "три", "translation": "三", "pos": "num", "grammar": {} },
      { "lemma": "четы́ре", "translation": "四", "pos": "num", "grammar": {} },
      { "lemma": "пять", "translation": "五", "pos": "num", "grammar": {} },
      { "lemma": "шесть", "translation": "六", "pos": "num", "grammar": {} },
      { "lemma": "семь", "translation": "七", "pos": "num", "grammar": {} },
      { "lemma": "во́семь", "translation": "八", "pos": "num", "grammar": {} },
      { "lemma": "де́вять", "translation": "九", "pos": "num", "grammar": {} },
      { "lemma": "де́сять", "translation": "十", "pos": "num", "grammar": {} },
      { "lemma": "оди́ннадцать", "translation": "十一", "pos": "num", "grammar": {} },
      { "lemma": "двена́дцать", "translation": "十二", "pos": "num", "grammar": {} }
    ]
  },
  {
    "category": "Prepositions & Particles (虚词)",
    "items": [  
      { "lemma": "да́же", "translation": "甚至", "pos": "other", "grammar": {},},
      { "lemma": "у", "translation": "在...旁边", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g (所有格)" },
      { "lemma": "от", "translation": "从.../由...", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g" },
      { "lemma": "в", "translation": "在...里/去...", "pos": "prep", "grammar": {} },
      { "lemma": "на", "translation": "往，向...上面", "pos": "prep", "grammar": {}, "syntax_note": "笔记补充：在...上面" },
      { "lemma": "с", "translation": "和.../从...", "pos": "prep", "grammar": {} },
      { "lemma": "к", "translation": "向.../朝...", "pos": "prep", "grammar": {} },
      { "lemma": "о", "translation": "关于", "pos": "prep", "grammar": {} },
      { "lemma": "и", "translation": "和/与", "pos": "other", "grammar": {} },
      { "lemma": "а", "translation": "而", "pos": "other", "grammar": {} },
      { "lemma": "но", "translation": "但是", "pos": "other", "grammar": {} },
      { "lemma": "и́ли", "translation": "或者", "pos": "other", "grammar": {} },
      { "lemma": "не", "translation": "不/没有", "pos": "other", "grammar": {} },
      { "lemma": "да", "translation": "是/对", "pos": "other", "grammar": {} },
      { "lemma": "нет", "translation": "不/不是", "pos": "other", "grammar": {} },
      { "lemma": "э́то", "translation": "这是", "pos": "other", "grammar": {} },
      { "lemma": "вот", "translation": "这就是/喏", "pos": "other", "grammar": {} },
      { "lemma": "ну", "translation": "喂/好吧 (语气词)", "pos": "other", "grammar": {} },
      { "lemma": "и", "translation": "和", "pos": "other", "grammar": {} },
      { "lemma": "ли", "translation": "是否，吗", "pos": "other", "grammar": {}, "syntax_note": "语气词"},
      { "lemma": "кро́ме того́", "translation": "除此之外，此外", "pos": "other", "grammar": {}, "syntax_note": ""},
      { "lemma": "жаль", "translation": "遗憾，可惜", "pos": "other", "grammar": {}, "syntax_note": "插入语或谓语", },
      { "lemma": "их", "translation": "他们的", "pos": "pron", "grammar": {}, "syntax_note": "物主代词" },
      { "lemma": "о́ба", "translation": "两者都", "pos": "num", "grammar": {}, "syntax_note": "集合数词" }
    ]
  }
];
