import { Category, PartOfSpeech } from './types';

export const POS_LABELS: Record<PartOfSpeech, { label: string; color: string }> = {
  noun: { label: 'Noun', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  verb: { label: 'Verb', color: 'bg-red-100 text-red-800 border-red-200' },
  adj: { label: 'Adjective', color: 'bg-green-100 text-green-800 border-green-200' },
  adv: { label: 'Adverb', color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  pron: { label: 'Pronoun', color: 'bg-purple-100 text-purple-800 border-purple-200' },
  prep: { label: 'Preposition', color: 'bg-gray-100 text-gray-800 border-gray-200' },
  num: { label: 'Number', color: 'bg-indigo-100 text-indigo-800 border-indigo-200' },
  other: { label: 'Other', color: 'bg-teal-100 text-teal-800 border-teal-200' },
};

// --- PASTE YOUR JSON DATA BELOW ---
export const INITIAL_DATA: Category[] = [
  {
    "category": "Time: Days, Months & Seasons (时间：星期/月份/季节)",
    "items": [
      { "lemma": "понедельник", "translation": "星期一", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вторник", "translation": "星期二", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "среда", "translation": "星期三", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "четверг", "translation": "星期四", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "воскресенье", "translation": "星期日", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "январь", "translation": "一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "февраль", "translation": "二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "март", "translation": "三月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "апрель", "translation": "四月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "май", "translation": "五月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "июнь", "translation": "六月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "июль", "translation": "七月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "август", "translation": "八月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сентябрь", "translation": "九月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "октябрь", "translation": "十月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ноябрь", "translation": "十一月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "декабрь", "translation": "十二月", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "весна", "translation": "春天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "лето", "translation": "夏天", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "осень", "translation": "秋天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "зима", "translation": "冬天", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "время", "translation": "时间", "pos": "noun", "grammar": { "gender": "n", "special": "-мя" } }
    ]
  },
  {
    "category": "Verbs (核心动词)",
    "items": [
      { "lemma": "учиться", "translation": "学习 (在某处)", "pos": "verb", "forms": ["учусь", "учишься", "учатся"], "syntax_note": "vi + 6g (在...)" },
      { "lemma": "учить", "translation": "学习 (背诵/教授)", "pos": "verb", "forms": ["учу", "учишь"], "syntax_note": "vt + 4g (学什么)" },
      { "lemma": "изучать", "translation": "研究，钻研", "pos": "verb", "forms": ["изучаю"], "syntax_note": "vt + 4g" },
      { "lemma": "заниматься", "translation": "从事，做功课", "pos": "verb", "forms": ["занимаюсь"], "syntax_note": "vi + 5g" },
      { "lemma": "любить", "translation": "爱", "pos": "verb", "forms": ["люблю", "любишь"], "syntax_note": "+ vt / n." },
      { "lemma": "хотеть", "translation": "想要", "pos": "verb", "forms": ["хочу", "хочешь", "хотят"], "syntax_note": "混合变位" },
      { "lemma": "говорить", "translation": "说", "pos": "verb", "forms": ["говорю", "говоришь"], "syntax_note": "vi/vt" },
      { "lemma": "сказать", "translation": "说 (命令式)", "pos": "verb", "forms": ["скажи", "скажите"], "syntax_note": "完成体" },
      { "lemma": "видеть", "translation": "看见", "pos": "verb", "forms": ["вижу", "видишь", "видят"], "syntax_note": "vt" },
      { "lemma": "смотреть", "translation": "看 (观看)", "pos": "verb", "forms": ["смотрю", "смотришь"], "syntax_note": "vt" },
      { "lemma": "слушать", "translation": "听", "pos": "verb", "forms": ["слушаю"], "syntax_note": "vt" },
      { "lemma": "слышать", "translation": "听见", "pos": "verb", "forms": ["слышу"], "syntax_note": "(图外补充，常与слушать对比)" },
      { "lemma": "стоять", "translation": "站立", "pos": "verb", "forms": ["стою", "стоишь"], "syntax_note": "vi + 6g" },
      { "lemma": "лежать", "translation": "平放，躺", "pos": "verb", "forms": ["лежу", "лежишь"], "syntax_note": "vi + 6g" },
      { "lemma": "сидеть", "translation": "坐", "pos": "verb", "forms": ["сижу", "сидишь"], "syntax_note": "vi" },
      { "lemma": "идти", "translation": "走 (正在进行)", "pos": "verb", "forms": ["иду", "идёшь"], "syntax_note": "Motion" },
      { "lemma": "ехать", "translation": "乘车去", "pos": "verb", "forms": ["еду", "едешь"], "syntax_note": "Motion" },
      { "lemma": "лететь", "translation": "飞", "pos": "verb", "forms": ["лечу", "летишь"], "syntax_note": "Motion" },
      { "lemma": "гулять", "translation": "散步", "pos": "verb", "forms": ["гуляю"], "syntax_note": "vi + 6g (在...散步)" },
      { "lemma": "вставать", "translation": "起床", "pos": "verb", "forms": ["встаю", "встаёшь"], "syntax_note": "" },
      { "lemma": "завтракать", "translation": "吃早饭", "pos": "verb", "forms": ["завтракаю"], "syntax_note": "" },
      { "lemma": "обедать", "translation": "吃午饭", "pos": "verb", "forms": ["обедаю"], "syntax_note": "" },
      { "lemma": "ужинать", "translation": "吃晚饭", "pos": "verb", "forms": ["ужинаю"], "syntax_note": "" },
      { "lemma": "покупать", "translation": "购买", "pos": "verb", "forms": ["покупаю"], "syntax_note": "vt" },
      { "lemma": "отдыхать", "translation": "休息", "pos": "verb", "forms": ["отдыхаю"], "syntax_note": "" },
      { "lemma": "играть", "translation": "玩，演奏", "pos": "verb", "forms": ["играю"], "syntax_note": "+ в 4g (玩球) / + на 6g (乐器)" },
      { "lemma": "петь", "translation": "唱", "pos": "verb", "forms": ["пою", "поёшь"], "syntax_note": "" },
      { "lemma": "танцевать", "translation": "跳舞", "pos": "verb", "forms": ["танцую", "танцуешь"], "syntax_note": "-ева- 变 -у-" },
      { "lemma": "фотографироваться", "translation": "拍照/合影", "pos": "verb", "forms": ["-руюсь"], "syntax_note": "反身动词" },
      { "lemma": "вспоминать", "translation": "回忆起", "pos": "verb", "forms": ["вспоминаю"], "syntax_note": "vt" },
      { "lemma": "собраться", "translation": "聚集，集合", "pos": "verb", "forms": ["собрался", "собрались"], "syntax_note": "过去时常用" },
      { "lemma": "мечтать", "translation": "梦想", "pos": "verb", "forms": ["мечтаю"], "syntax_note": "+ о 6g" },
      { "lemma": "ждать", "translation": "等待", "pos": "verb", "forms": ["жду", "ждёшь"], "syntax_note": "+ 2g/4g" },
      { "lemma": "родиться", "translation": "出生", "pos": "verb", "forms": ["родился"], "syntax_note": "过去时" },
      { "lemma": "звать", "translation": "叫，称呼", "pos": "verb", "forms": ["зовут"], "syntax_note": "Меня зовут..." }
    ]
  },
  {
    "category": "Nouns (People & Family) (名词：人、家庭、动物)",
    "items": [
      { "lemma": "семья", "translation": "家庭", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "родители", "translation": "父母", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "отец", "translation": "父亲", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "мать", "translation": "母亲", "pos": "noun", "grammar": { "gender": "f", "special": "soft" } },
      { "lemma": "папа", "translation": "爸爸", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "мама", "translation": "妈妈", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дедушка", "translation": "爷爷/外公", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бабушка", "translation": "奶奶/外婆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дядя", "translation": "叔叔/舅舅", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тётя", "translation": "阿姨/姑姑", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "сын", "translation": "儿子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "дочь", "translation": "女儿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "брат", "translation": "兄弟", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сестра", "translation": "姐妹", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дети", "translation": "孩子们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "человек", "translation": "人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "люди", "translation": "人们", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "мужчина", "translation": "男人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "женщина", "translation": "女人 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "мальчик", "translation": "男孩", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "девушка", "translation": "姑娘", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "друг", "translation": "朋友", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "товарищ", "translation": "同志/同学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сосед", "translation": "邻居 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гость", "translation": "客人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "преподаватель", "translation": "大学教师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учитель", "translation": "中小学男老师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "учительница", "translation": "中小学女老师", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "студент", "translation": "大学生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "школьник", "translation": "学生 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ученик", "translation": "中小学生(男)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ученица", "translation": "中小学生(女)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "химик", "translation": "化学家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "художник", "translation": "画家/艺术家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "писатель", "translation": "作家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "врач", "translation": "医生", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "космонавт", "translation": "宇航员", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "шофёр", "translation": "司机", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "москвич", "translation": "莫斯科人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кот", "translation": "公猫", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "собака", "translation": "狗", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "утка", "translation": "鸭子", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "повар", "translation": "厨师", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "поэт", "translation": "诗人", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "музыкант", "translation": "音乐家", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "подруга", "translation": "女朋友", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：(女性)朋友" },
      { "lemma": "группа", "translation": "班级/小组", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记：组/班" }
    ]
  },
  {
    "category": "Nouns (Food & Drink) (名词：饮食)",
    "items": [
      { "lemma": "суп", "translation": "汤", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сок", "translation": "果汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "соус", "translation": "调味汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "уксус", "translation": "醋", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сахар", "translation": "糖", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "торт", "translation": "蛋糕", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ананас", "translation": "菠萝", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "банан", "translation": "香蕉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "капуста", "translation": "白菜", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "томат", "translation": "番茄", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：番茄酱" }
    ]
  },
  {
    "category": "Nouns (Places & Objects) (名词：地点与物品)",
    "items": [
      { "lemma": "окно", "translation": "窗户", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "касса", "translation": "收款台", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：售票处" },
      { "lemma": "мост", "translation": "桥", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "банк", "translation": "银行", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "завод", "translation": "工厂", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "重音在后" },
      { "lemma": "рынок", "translation": "市场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "сад", "translation": "花园", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "复数：сады́ (重音后移)" },
      { "lemma": "выставка", "translation": "展览/展览会", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "фонтан", "translation": "喷泉", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "бар", "translation": "酒吧", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "вход", "translation": "入口", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "反义词笔记：выход (出口)" },
      { "lemma": "кафе", "translation": "咖啡馆", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：外来词，中性，不变格" },
      { "lemma": "фото", "translation": "照片", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" }, "syntax_note": "笔记强调：中性，不变化" },
      { "lemma": "сумка", "translation": "手提包", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：书包" },
      { "lemma": "стакан", "translation": "杯子/玻璃杯", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ваза", "translation": "花瓶", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "кофта", "translation": "女短上衣", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "университет", "translation": "大学", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "институт", "translation": "学院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "школа", "translation": "学校 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "библиотека", "translation": "图书馆", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "магазин", "translation": "商店", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "столовая", "translation": "食堂", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "кухня", "translation": "厨房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "буфет", "translation": "小卖部", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "театр", "translation": "剧院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кинотеатр", "translation": "电影院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "музей", "translation": "博物馆", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "стадион", "translation": "体育场", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "парк", "translation": "公园", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "больница", "translation": "医院", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "санаторий", "translation": "疗养院", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "общежитие", "translation": "宿舍", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "квартира", "translation": "公寓/套房", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "комната", "translation": "房间", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "дворец", "translation": "宫殿", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "площадь", "translation": "广场", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "улица", "translation": "街道", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "проспект", "translation": "大街/大道", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "деревня", "translation": "农村", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "метро", "translation": "地铁", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "такси", "translation": "出租车", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "автобус", "translation": "公交车", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "словарь", "translation": "字典", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "тетрадь", "translation": "练习本", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "учебник", "translation": "教科书", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "письмо", "translation": "信", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "газета", "translation": "报纸", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "журнал", "translation": "杂志", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "текст", "translation": "课文", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "упражнение", "translation": "练习/习题", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "слово", "translation": "单词", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "предложение", "translation": "句子 (图外补充)", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "вопрос", "translation": "问题", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "ответ", "translation": "回答 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "экзамен", "translation": "考试 (图外补充)", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "деньги", "translation": "钱", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "рубль", "translation": "卢布", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "цветы", "translation": "花", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "очки", "translation": "眼镜", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "брюки", "translation": "裤子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "туфли", "translation": "鞋子", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "обувь", "translation": "鞋类(总称)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "пальто", "translation": "大衣", "pos": "noun", "grammar": { "gender": "n", "special": "indeclinable" } },
      { "lemma": "плащ", "translation": "风衣/雨衣", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "гитара", "translation": "吉他", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "шахматы", "translation": "象棋", "pos": "noun", "grammar": { "plural_only": true } },
      { "lemma": "мясо", "translation": "肉", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "рыба", "translation": "鱼 (图外补充)", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "хлеб", "translation": "面包", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "молоко", "translation": "牛奶", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "чай", "translation": "茶", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "кофе", "translation": "咖啡", "pos": "noun", "grammar": { "gender": "m", "special": "indeclinable" } },
      { "lemma": "вода", "translation": "水", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "сок", "translation": "果汁", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "пиво", "translation": "啤酒", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "рис", "translation": "米饭", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "конфета", "translation": "糖果", "pos": "noun", "grammar": { "gender": "f" } }
    ]
  },
{
    "category": "Nouns(Body, Abstract & Nature) (身体、抽象与自然)",
    "items": [
      { "lemma": "нос", "translation": "鼻子", "pos": "noun", "grammar": { "gender": "m" } },
      { "lemma": "нога", "translation": "脚/腿", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "рука", "translation": "手", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "ухо", "translation": "耳朵", "pos": "noun", "grammar": { "gender": "n" } },
      { "lemma": "ум", "translation": "智慧/智力", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：聪明" },
      { "lemma": "сон", "translation": "梦", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记补充：睡眠" },
      { "lemma": "работа", "translation": "工作", "pos": "noun", "grammar": { "gender": "f" }, "syntax_note": "笔记补充：作品/著作" },
      { "lemma": "спорт", "translation": "体育", "pos": "noun", "grammar": { "gender": "m" }, "syntax_note": "笔记：运动" },
      { "lemma": "погода", "translation": "天气", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "гора", "translation": "山", "pos": "noun", "grammar": { "gender": "f" } },
      { "lemma": "космос", "translation": "宇宙", "pos": "noun", "grammar": { "gender": "m" } }
    ]
  },
  {
    "category": "Adjectives (形容词)",
    "items": [
      { "lemma": "большой", "translation": "大的", "pos": "adj", "grammar": {} },
      { "lemma": "маленький", "translation": "小的", "pos": "adj", "grammar": {} },
      { "lemma": "хороший", "translation": "好的", "pos": "adj", "grammar": {} },
      { "lemma": "плохой", "translation": "坏的", "pos": "adj", "grammar": {} },
      { "lemma": "красивый", "translation": "美丽的", "pos": "adj", "grammar": {} },
      { "lemma": "интересный", "translation": "有趣的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "новый", "translation": "新的", "pos": "adj", "grammar": {} },
      { "lemma": "старый", "translation": "旧的/老的", "pos": "adj", "grammar": {} },
      { "lemma": "молодой", "translation": "年轻的", "pos": "adj", "grammar": {} },
      { "lemma": "старший", "translation": "年长的", "pos": "adj", "grammar": {} },
      { "lemma": "младший", "translation": "年幼的", "pos": "adj", "grammar": {} },
      { "lemma": "добрый", "translation": "善良的", "pos": "adj", "grammar": {} },
      { "lemma": "весёлый", "translation": "快乐的", "pos": "adj", "grammar": {} },
      { "lemma": "умный", "translation": "聪明的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "трудный", "translation": "困难的", "pos": "adj", "grammar": {} },
      { "lemma": "лёгкий", "translation": "容易的/轻的", "pos": "adj", "grammar": {} },
      { "lemma": "дорогой", "translation": "贵的/亲爱的", "pos": "adj", "grammar": {} },
      { "lemma": "дешёвый", "translation": "便宜的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "горячий", "translation": "热的", "pos": "adj", "grammar": {} },
      { "lemma": "холодный", "translation": "冷的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "свежий", "translation": "新鲜的", "pos": "adj", "grammar": {} },
      { "lemma": "чистый", "translation": "干净的", "pos": "adj", "grammar": {} },
      { "lemma": "красный", "translation": "红色的", "pos": "adj", "grammar": {} },
      { "lemma": "синий", "translation": "蓝色的", "pos": "adj", "grammar": { "special": "soft" } },
      { "lemma": "белый", "translation": "白色的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "чёрный", "translation": "黑色的 (图外补充)", "pos": "adj", "grammar": {} },
      { "lemma": "русский", "translation": "俄罗斯的", "pos": "adj", "grammar": {} },
      { "lemma": "китайский", "translation": "中国的", "pos": "adj", "grammar": {} },
      { "lemma": "английский", "translation": "英国的", "pos": "adj", "grammar": {} },
      { "lemma": "пекинский", "translation": "北京的", "pos": "adj", "grammar": {} },
      { "lemma": "московский", "translation": "莫斯科的", "pos": "adj", "grammar": {} },
      { "lemma": "домашний", "translation": "家庭的", "pos": "adj", "grammar": { "special": "soft" } }
    ]
  },
  {
    "category": "Adverbs & Others (副词、代词及其他)",
    "items": [
      { "lemma": "пока", "translation": "暂时/当...时候", "pos": "adv", "grammar": {}, "syntax_note": "口语常用：回头见" },
      { "lemma": "опасно", "translation": "危险", "pos": "adv", "grammar": {} },
      { "lemma": "рано", "translation": "早", "pos": "adv", "grammar": {} },
      { "lemma": "сухо", "translation": "干燥", "pos": "adv", "grammar": {} },
      { "lemma": "тут", "translation": "这里", "pos": "adv", "grammar": {}, "syntax_note": "口语常用" },
      { "lemma": "там", "translation": "那里", "pos": "adv", "grammar": {} },
      { "lemma": "потом", "translation": "然后", "pos": "adv", "grammar": {} },
      { "lemma": "поэтому", "translation": "所以/因此", "pos": "adv", "grammar": {} },
      { "lemma": "у", "translation": "在...旁边", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g (所有格)" },
      { "lemma": "от", "translation": "从.../由...", "pos": "prep", "grammar": {}, "syntax_note": "+ 2g" },
      { "lemma": "стоп", "translation": "停", "pos": "other", "grammar": {}, "syntax_note": "图片手写补充" },
      { "lemma": "хорошо", "translation": "好", "pos": "adv", "grammar": {} },
      { "lemma": "плохо", "translation": "坏/不好", "pos": "adv", "grammar": {} },
      { "lemma": "быстро", "translation": "快 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "медленно", "translation": "慢 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "громко", "translation": "大声地 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "тихо", "translation": "安静地", "pos": "adv", "grammar": {} },
      { "lemma": "вкусно", "translation": "好吃", "pos": "adv", "grammar": {} },
      { "lemma": "интересно", "translation": "有趣", "pos": "adv", "grammar": {} },
      { "lemma": "сегодня", "translation": "今天", "pos": "adv", "grammar": {} },
      { "lemma": "вчера", "translation": "昨天", "pos": "adv", "grammar": {} },
      { "lemma": "завтра", "translation": "明天", "pos": "adv", "grammar": {} },
      { "lemma": "сейчас", "translation": "现在", "pos": "adv", "grammar": {} },
      { "lemma": "потом", "translation": "以后/随后", "pos": "adv", "grammar": {} },
      { "lemma": "раньше", "translation": "以前", "pos": "adv", "grammar": {} },
      { "lemma": "давно", "translation": "很久以前/许久", "pos": "adv", "grammar": {} },
      { "lemma": "недавно", "translation": "不久前", "pos": "adv", "grammar": {} },
      { "lemma": "здесь", "translation": "这里", "pos": "adv", "grammar": {} },
      { "lemma": "там", "translation": "那里 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "домой", "translation": "回家(去)", "pos": "adv", "grammar": {} },
      { "lemma": "дома", "translation": "在家 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "очень", "translation": "非常", "pos": "adv", "grammar": {} },
      { "lemma": "много", "translation": "多", "pos": "adv", "grammar": {} },
      { "lemma": "мало", "translation": "少 (图外补充)", "pos": "adv", "grammar": {} },
      { "lemma": "только", "translation": "只/仅仅", "pos": "adv", "grammar": {} },
      { "lemma": "уже", "translation": "已经", "pos": "adv", "grammar": {} },
      { "lemma": "ещё", "translation": "还/再", "pos": "adv", "grammar": {} },
      { "lemma": "тоже", "translation": "也", "pos": "adv", "grammar": {} },
      { "lemma": "почему", "translation": "为什么", "pos": "adv", "grammar": {} },
      { "lemma": "потому что", "translation": "因为 (图外补充)", "pos": "pron", "grammar": {} },
      { "lemma": "кто", "translation": "谁", "pos": "pron", "grammar": {} },
      { "lemma": "что", "translation": "什么", "pos": "pron", "grammar": {} },
      { "lemma": "где", "translation": "在哪里", "pos": "adv", "grammar": {} },
      { "lemma": "куда", "translation": "去哪里", "pos": "adv", "grammar": {} },
      { "lemma": "когда", "translation": "什么时候", "pos": "adv", "grammar": {} },
      { "lemma": "как", "translation": "怎样", "pos": "adv", "grammar": {} },
      { "lemma": "сколько", "translation": "多少", "pos": "adv", "grammar": {} },
      { "lemma": "какой", "translation": "什么样的", "pos": "pron", "grammar": {} },
      { "lemma": "чей", "translation": "谁的", "pos": "pron", "grammar": {} },
      { "lemma": "свой", "translation": "自己的", "pos": "pron", "grammar": {} },
      { "lemma": "спасибо", "translation": "谢谢", "pos": "other", "grammar": {} },
      { "lemma": "пожалуйста", "translation": "请/不客气", "pos": "other", "grammar": {} },
      { "lemma": "привет", "translation": "你好(非正式)", "pos": "other", "grammar": {} },
      { "lemma": "здравствуйте", "translation": "您好(正式)", "pos": "other", "grammar": {} },
      { "lemma": "до свидания", "translation": "再见", "pos": "other", "grammar": {} }
    ]
  },
  {
    "category": "Numbers (数字)",
    "items": [
      { "lemma": "сто", "translation": "一百", "pos": "num", "grammar": {} },
      { "lemma": "один", "translation": "一", "pos": "num", "grammar": {} },
      { "lemma": "два", "translation": "二", "pos": "num", "grammar": {} },
      { "lemma": "три", "translation": "三", "pos": "num", "grammar": {} },
      { "lemma": "четыре", "translation": "四", "pos": "num", "grammar": {} },
      { "lemma": "пять", "translation": "五", "pos": "num", "grammar": {} },
      { "lemma": "шесть", "translation": "六", "pos": "num", "grammar": {} },
      { "lemma": "семь", "translation": "七", "pos": "num", "grammar": {} },
      { "lemma": "восемь", "translation": "八", "pos": "num", "grammar": {} },
      { "lemma": "девять", "translation": "九", "pos": "num", "grammar": {} },
      { "lemma": "десять", "translation": "十", "pos": "num", "grammar": {} },
      { "lemma": "одиннадцать", "translation": "十一", "pos": "num", "grammar": {} },
      { "lemma": "двенадцать", "translation": "十二", "pos": "num", "grammar": {} }
    ]
  }
];